### ISSUE TITLE
ルーム参加時に、「ルームに参加」ボタンを複数回押すと、同じプレイヤーが複数人追加される

### ISSUE THREAD

**Issue by fukamikensuke** [hacku-chamomilla/doutankyohi-front-end#220]
## 🐛 概要
- roomId入力し、プレイヤーデータを入力する際にダブルクリック以上を行うと、同じ部屋に同じひとが複数人入る
## 📸 スクリーンショット
![image](https://user-images.githubusercontent.com/77095417/229406742-33065e96-12aa-4049-8f23-d42ee3871056.png)

https://user-images.githubusercontent.com/77095417/229407660-f377c7ee-0667-4c36-8078-98e27fa763ab.mp4

## 👀 再現手順

1. roomidを入力する
2. プレイヤーネームを入力する
3. 参加するボタンを画面が切り替割るまでクリックを行う
4. クリックするだけ入室する

## 🎨 期待する挙動
- ダブルクリックをしても、入室できるのは一回まで
## 📦️ 環境

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge

## ✅ タスク

- [ ] xxx

**Comment by ltoppyl** [comment]
### 解決案のメモ
- ボタンを1回押したら、下画像のような感じでボタンをローディングにして2回目以降を押せなくする 
![image](https://user-images.githubusercontent.com/68209431/229407402-0a637d0f-3330-4957-918f-7f0a0de7a387.png)

**Comment by ltoppyl** [comment]
ルーム作成時だけではなく、色んなところで起きそうだから、他のとこでも起きないかの調査もしたい
